name: Unity Star
favicon: null
layout_spectrum: 0.6428103793878108
typography_spectrum: 0.8324020479340106
title: 'Unity Star - Film-making, literary, music production, technology'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3030624631792307
  lightness: 0.3072255889419466
  saturation: 0.26825174130499363
  rhythmicContrast: 0.6232152108568698
purpose: []
